package org.openmbee.mms.core.config;

public enum Privileges {

    ORG_READ,
    ORG_EDIT,
    ORG_UPDATE_PERMISSIONS,
    ORG_READ_PERMISSIONS,
    ORG_CREATE_PROJECT,
    ORG_DELETE,
    PROJECT_READ,
    PROJECT_EDIT,
    PROJECT_READ_COMMITS,
    PROJECT_CREATE_BRANCH,
    PROJECT_DELETE,
    PROJECT_UPDATE_PERMISSIONS,
    PROJECT_READ_PERMISSIONS,
    PROJECT_CREATE_WEBHOOKS,
    BRANCH_READ,
    BRANCH_EDIT_CONTENT,
    BRANCH_DELETE,
    BRANCH_UPDATE_PERMISSIONS,
    BRANCH_READ_PERMISSIONS

}
